//all country objects
export const countries = [
    { country: "Afghanistan", code: "+93", currency: "AFN", availability: "private" },
    { country: "Albania", code: "+355", currency: "ALL", availability: "private" },
    { country: "Algeria", code: "+213", currency: "DZD", availability: "private" },
    { country: "Andorra", code: "+376", currency: "EUR", availability: "private" },
    { country: "Angola", code: "+244", currency: "AOA", availability: "private" },
    { country: "Antigua and Barbuda", code: "+1-268", currency: "XCD", availability: "private" },
    { country: "Argentina", code: "+54", currency: "ARS", availability: "private" },
    { country: "Armenia", code: "+374", currency: "AMD", availability: "private" },
    { country: "Australia", code: "+61", currency: "AUD", availability: "private" },
    { country: "Austria", code: "+43", currency: "EUR", availability: "private" },
    { country: "Azerbaijan", code: "+994", currency: "AZN", availability: "private" },
    { country: "Bahamas", code: "+1-242", currency: "BSD", availability: "private" },
    { country: "Bahrain", code: "+973", currency: "BHD", availability: "private" },
    { country: "Bangladesh", code: "+880", currency: "BDT", availability: "private" },
    { country: "Barbados", code: "+1-246", currency: "BBD", availability: "private" },
    { country: "Belarus", code: "+375", currency: "BYN", availability: "private" },
    { country: "Belgium", code: "+32", currency: "EUR", availability: "private" },
    { country: "Belize", code: "+501", currency: "BZD", availability: "private" },
    { country: "Benin", code: "+229", currency: "XOF", availability: "private" },
    { country: "Bhutan", code: "+975", currency: "BTN", availability: "private" },
    { country: "Bolivia", code: "+591", currency: "BOB", availability: "private" },
    { country: "Bosnia and Herzegovina", code: "+387", currency: "BAM", availability: "private" },
    { country: "Botswana", code: "+267", currency: "BWP", availability: "private" },
    { country: "Brazil", code: "+55", currency: "BRL", availability: "private" },
    { country: "Brunei", code: "+673", currency: "BND", availability: "private" },
    { country: "Bulgaria", code: "+359", currency: "BGN", availability: "private" },
    { country: "Burkina Faso", code: "+226", currency: "XOF", availability: "private" },
    { country: "Burundi", code: "+257", currency: "BIF", availability: "private" },
    { country: "Cabo Verde", code: "+238", currency: "CVE", availability: "private" },
    { country: "Cambodia", code: "+855", currency: "KHR", availability: "private" },
    { country: "Cameroon", code: "+237", currency: "CDF", availability: "private" },
    { country: "Canada", code: "+1", currency: "CAD", availability: "private" },
    { country: "Central African Republic", code: "+236", currency: "CFA", availability: "private" },
    { country: "Chad", code: "+235", currency: "CDF", availability: "private" },
    { country: "Chile", code: "+56", currency: "CLP", availability: "private" },
    { country: "China", code: "+86", currency: "CNY", availability: "private" },
    { country: "Colombia", code: "+57", currency: "COP", availability: "private" },
    { country: "Comoros", code: "+269", currency: "KMF", availability: "private" },
    { country: "Congo, Democratic Republic of the", code: "+243", currency: "CDF", availability: "private" },
    { country: "Congo, Republic of the", code: "+242", currency: "CDF", availability: "private" },
    { country: "Costa Rica", code: "+506", currency: "CRC", availability: "private" },
    { country: "Cote d'Ivoire", code: "+225", currency: "XOF", availability: "private" },
    { country: "Croatia", code: "+385", currency: "HRK", availability: "private" },
    { country: "Cuba", code: "+53", currency: "CUP", availability: "private" },
    { country: "Cyprus", code: "+357", currency: "EUR", availability: "private" },
    { country: "Czech Republic", code: "+420", currency: "CZK", availability: "private" },
    { country: "Denmark", code: "+45", currency: "DKK", availability: "private" },
    { country: "Djibouti", code: "+253", currency: "DJF", availability: "private" },
    { country: "Dominica", code: "+1-767", currency: "XCD", availability: "private" },
    { country: "Dominican Republic", code: "+1-809", currency: "DOP", availability: "private" },
    { country: "Ecuador", code: "+593", currency: "USD", availability: "private" },
    { country: "Egypt", code: "+20", currency: "EGP", availability: "private" },
    { country: "El Salvador", code: "+503", currency: "SVC", availability: "private" },
    { country: "Equatorial Guinea", code: "+240", currency: "GNF", availability: "private" },
    { country: "Eritrea", code: "+291", currency: "ERN", availability: "private" },
    { country: "Estonia", code: "+372", currency: "EEK", availability: "private" },
    { country: "Eswatini", code: "+268", currency: "SZL", availability: "private" },
    { country: "Ethiopia", code: "+251", currency: "ETB", availability: "private" },
    { country: "Fiji", code: "+679", currency: "FJD", availability: "private" },
    { country: "Finland", code: "+358", currency: "EUR", availability: "private" },
    { country: "France", code: "+33", currency: "EUR", availability: "private" },
    { country: "Gabon", code: "+241", currency: "GAB", availability: "private" },
    { country: "Gambia", code: "+220", currency: "GMD", availability: "private" },
    { country: "Georgia", code: "+995", currency: "GEL", availability: "private" },
    { country: "Germany", code: "+49", currency: "EUR", availability: "private" },
    { country: "Ghana", code: "+233", currency: "GHS", mno: ["MTN Ghana", "AIRTELTIGO AT", "TELECEL"], availability: "private" },
    { country: "Greece", code: "+30", currency: "EUR", availability: "private" },
    { country: "Grenada", code: "+1-473", currency: "XCD", availability: "private" },
    { country: "Guatemala", code: "+502", currency: "GTQ", availability: "private" },
    { country: "Guinea", code: "+224", currency: "GNF", availability: "private" },
    { country: "Guinea-Bissau", code: "+245", currency: "GNF", availability: "private" },
    { country: "Guyana", code: "+592", currency: "GYD", availability: "private" },
    { country: "Haiti", code: "+509", currency: "HTG", availability: "private" },
    { country: "Honduras", code: "+504", currency: "HNL", availability: "private" },
    { country: "Hungary", code: "+36", currency: "HUF", availability: "private" },
    { country: "Iceland", code: "+354", currency: "ISK", availability: "private" },
    { country: "India", code: "+91", currency: "INR", availability: "private" },
    { country: "Indonesia", code: "+62", currency: "IDR", availability: "private" },
    { country: "Iran", code: "+98", currency: "IRR", availability: "private" },
    { country: "Iraq", code: "+964", currency: "IQD", availability: "private" },
    { country: "Ireland", code: "+353", currency: "EUR", availability: "private" },
    { country: "Israel", code: "+972", currency: "ILS", availability: "private" },
    { country: "Italy", code: "+39", currency: "EUR", availability: "private" },
    { country: "Jamaica", code: "+1-876", currency: "JMD", availability: "private" },
    { country: "Japan", code: "+81", currency: "JPY", availability: "private" },
    { country: "Jordan", code: "+962", currency: "JOD", availability: "private" },
    { country: "Kazakhstan", code: "+7", currency: "KZT", availability: "private" },
    { country: "Kenya", code: "+254", currency: "KES", availability: "public" },
    { country: "Kiribati", code: "+686", currency: "AUD", availability: "private" },
    { country: "Korea, North", code: "+850", currency: "KPW", availability: "private" },
    { country: "Korea, South", code: "+82", currency: "KRW", availability: "private" },
    { country: "Kosovo", code: "+383", currency: "EUR", availability: "private" },
    { country: "Kuwait", code: "+965", currency: "KWD", availability: "private" },
    { country: "Kyrgyzstan", code: "+996", currency: "KGS", availability: "private" },
    { country: "Laos", code: "+856", currency: "LAK", availability: "private" },
    { country: "Latvia", code: "+371", currency: "EUR", availability: "private" },
    { country: "Lebanon", code: "+961", currency: "LBP", availability: "private" },
    { country: "Lesotho", code: "+266", currency: "LSL", availability: "private" },
    { country: "Liberia", code: "+231", currency: "LRD", availability: "private" },
    { country: "Libya", code: "+218", currency: "LYD", availability: "private" },
    { country: "Liechtenstein", code: "+423", currency: "CHF", availability: "private" },
    { country: "Lithuania", code: "+370", currency: "LTL", availability: "private" },
    { country: "Luxembourg", code: "+352", currency: "EUR", availability: "private" },
    { country: "Madagascar", code: "+261", currency: "MGA", availability: "private" },
    { country: "Malawi", code: "+265", currency: "MWK", availability: "private" },
    { country: "Malaysia", code: "+60", currency: "MYR", availability: "private" },
    { country: "Maldives", code: "+960", currency: "MVR", availability: "private" },
    { country: "Mali", code: "+223", currency: "CFA", availability: "private" },
    { country: "Malta", code: "+356", currency: "EUR", availability: "private" },
    { country: "Marshall Islands", code: "+692", currency: "USD", availability: "private" },
    { country: "Mauritania", code: "+222", currency: "MRO", availability: "private" },
    { country: "Mauritius", code: "+230", currency: "MUR", availability: "private" },
    { country: "Mexico", code: "+52", currency: "MXN", availability: "private" },
    { country: "Micronesia", code: "+691", currency: "USD", availability: "private" },
    { country: "Moldova", code: "+373", currency: "MDL", availability: "private" },
    { country: "Monaco", code: "+377", currency: "EUR", availability: "private" },
    { country: "Mongolia", code: "+976", currency: "MNT", availability: "private" },
    { country: "Montenegro", code: "+382", currency: "EUR", availability: "private" },
    { country: "Morocco", code: "+212", currency: "MAD", availability: "private" },
    { country: "Mozambique", code: "+258", currency: "MZN", availability: "private" },
    { country: "Myanmar", code: "+95", currency: "MMK", availability: "private" },
    { country: "Namibia", code: "+264", currency: "NAD", availability: "private" },
    { country: "Nauru", code: "+674", currency: "AUD", availability: "private" },
    { country: "Nepal", code: "+977", currency: "NPR", availability: "private" },
    { country: "Netherlands", code: "+31", currency: "EUR", availability: "private" },
    { country: "New Zealand", code: "+64", currency: "NZD", availability: "private" },
    { country: "Nicaragua", code: "+505", currency: "NIO", availability: "private" },
    { country: "Niger", code: "+227", currency: "NGN", availability: "private" },
    { country: "Nigeria", code: "+234", currency: "NGN", availability: "private" },
    { country: "North Macedonia", code: "+389", currency: "MKD", availability: "private" },
    { country: "Norway", code: "+47", currency: "NOK", availability: "private" },
    { country: "Oman", code: "+968", currency: "OMR", availability: "private" },
    { country: "Pakistan", code: "+92", currency: "PKR", availability: "private" },
    { country: "Palau", code: "+680", currency: "USD", availability: "private" },
    { country: "Palestine", code: "+970", currency: "ILS", availability: "private" },
    { country: "Panama", code: "+507", currency: "PAB", availability: "private" },
    { country: "Papua New Guinea", code: "+675", currency: "PGK", availability: "private" },
    { country: "Paraguay", code: "+595", currency: "PYG", availability: "private" },
    { country: "Peru", code: "+51", currency: "PEN", availability: "private" },
    { country: "Philippines", code: "+63", currency: "PHP", availability: "private" },
    { country: "Poland", code: "+48", currency: "PLN", availability: "private" },
    { country: "Portugal", code: "+351", currency: "EUR", availability: "private" },
    { country: "Qatar", code: "+974", currency: "QAR", availability: "private" },
    { country: "Romania", code: "+40", currency: "RON", availability: "private" },
    { country: "Russia", code: "+7", currency: "RUB", availability: "private" },
    { country: "Rwanda", code: "+250", currency: "RWF", availability: "public" },
    { country: "Saint Kitts and Nevis", code: "+1-869", currency: "XCD", availability: "private" },
    { country: "Saint Lucia", code: "+1-758", currency: "XCD", availability: "private" },
    { country: "Saint Vincent and the Grenadines", code: "+1-784", currency: "XCD", availability: "private" },
    { country: "Samoa", code: "+685", currency: "WST", availability: "private" },
    { country: "San Marino", code: "+378", currency: "EUR", availability: "private" },
    { country: "Sao Tome and Principe", code: "+239", currency: "STN", availability: "private" },
    { country: "Saudi Arabia", code: "+966", currency: "SAR", availability: "private" },
    { country: "Senegal", code: "+221", currency: "XOF", availability: "private" },
    { country: "Serbia", code: "+381", currency: "RSD", availability: "private" },
    { country: "Seychelles", code: "+248", currency: "SCR", availability: "private" },
    { country: "Sierra Leone", code: "+232", currency: "SLL", availability: "private" },
    { country: "Singapore", code: "+65", currency: "SGD", availability: "private" },
    { country: "Slovakia", code: "+421", currency: "EUR", availability: "private" },
    { country: "Slovenia", code: "+386", currency: "EUR", availability: "private" },
    { country: "Solomon Islands", code: "+677", currency: "SBD", availability: "private" },
    { country: "Somalia", code: "+252", currency: "SOS", availability: "private" },
    { country: "South Africa", code: "+27", currency: "ZAR", availability: "private" },
    { country: "South Sudan", code: "+211", currency: "SSP", availability: "private" },
    { country: "Spain", code: "+34", currency: "EUR", availability: "private" },
    { country: "Sri Lanka", code: "+94", currency: "LKR", availability: "private" },
    { country: "Sudan", code: "+249", currency: "SDG", availability: "private" },
    { country: "Suriname", code: "+597", currency: "SRD", availability: "private" },
    { country: "Sweden", code: "+46", currency: "SEK", availability: "private" },
    { country: "Switzerland", code: "+41", currency: "CHF", availability: "private" },
    { country: "Syria", code: "+963", currency: "SYP", availability: "private" },
    { country: "Taiwan", code: "+886", currency: "TWD", availability: "private" },
    { country: "Tajikistan", code: "+992", currency: "TJS", availability: "private" },
    { country: "Tanzania", code: "+255", currency: "TZS", availability: "public" },
    { country: "Thailand", code: "+66", currency: "THB", availability: "private" },
    { country: "Timor-Leste", code: "+670", currency: "USD", availability: "private" },
    { country: "Togo", code: "+228", currency: "XOF", availability: "private" },
    { country: "Tonga", code: "+676", currency: "TOP", availability: "private" },
    { country: "Trinidad and Tobago", code: "+1-868", currency: "TTD", availability: "private" },
    { country: "Tunisia", code: "+216", currency: "TND", availability: "private" },
    { country: "Turkey", code: "+90", currency: "TRY", availability: "private" },
    { country: "Turkmenistan", code: "+993", currency: "TMT", availability: "private" },
    { country: "Tuvalu", code: "+688", currency: "AUD", availability: "private" },
    { country: "Uganda", code: "+256", currency: "UGX", mno: ["MTN Uganda", "AIRTEL Uganda"], availability: "public" },
    { country: "Ukraine", code: "+380", currency: "UAH", availability: "private" },
    { country: "United Arab Emirates", code: "+971", currency: "AED", availability: "private" },
    { country: "United Kingdom", code: "+44", currency: "GBP", availability: "private" },
    { country: "United States", code: "+1", currency: "USD", availability: "private" },
    { country: "Uruguay", code: "+598", currency: "UYU", availability: "private" },
    { country: "Uzbekistan", code: "+998", currency: "UZS", availability: "private" },
    { country: "Vanuatu", code: "+678", currency: "VUV", availability: "private" },
    { country: "Vatican City", code: "+379", currency: "EUR", availability: "private" },
    { country: "Venezuela", code: "+58", currency: "VES", availability: "private" },
    { country: "Vietnam", code: "+84", currency: "VND", availability: "private" },
    { country: "Yemen", code: "+967", currency: "YER", availability: "private" },
    { country: "Zambia", code: "+260", currency: "ZMW", availability: "private" },
    { country: "Zimbabwe", code: "+263", currency: "ZWL", availability: "private" },
];
// Function to get public countries
export const getPublicCountries = () => {
    return countries.filter((c) => c.availability === "public");
};